### ISSUE TITLE
Task POST 500 Error

### ISSUE THREAD

**Issue by Conqerorior** [ThatCoderMan/AlfaBankHackathon#42]
DETAIL:  Ключ (pdp_id)=(1) отсутствует в таблице "pdp".
[SQL: INSERT INTO task (pdp_id, type_id, status_id, title, description, link, chief_comment, employee_comment, starting_date, deadline) VALUES ($1::INTEGER, $2::INTEGER, $3::INTEGER, $4::VARCHAR, $5::VARCHAR, $6::VARCHAR, $7::VARCHAR, $8::VARCHAR, $9::DATE, $10::DATE) RETURNING task.id]

При создании Task с несуществующим pdp_id выводится ошибка 500 Error: Internal Server Error

**Comment by ThatCoderMan** [comment]
ошибка относится к [данному issue](https://github.com/ThatCoderMan/AlfaBankHackathon/issues/28).
